name: "🧠 Prompt Change Request"
description: "Request or describe a change to a prompt or prompt-related logic"
title: "[REFACTOR] "
labels: ["enhancement"]
body:
  - type: textarea
    id: prompt-description
    attributes:
      label: Prompt Description
      description: Which prompt or prompt-related component needs to be changed?
      placeholder: "e.g., system prompt for chat assistant, code generation prompt, etc."
    validations:
      required: true

  - type: textarea
    id: proposed-changes
    attributes:
      label: Proposed Changes
      description: The changes to be made in the prompt
      placeholder: "- [ ] Include rules of BI-RADS 6 to the prompt..."
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of inputs and expected outputs if applicable
      placeholder: |
        Input: ...
        Expected output: ...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the prompt change request here
    validations:
      required: false
