name: "📝 Task Request"
description: "Suggest a new task for the system"
title: "[TASK] "
labels: []
body:
  - type: textarea
    id: task-description
    attributes:
      label: Task Description
      description: Provide a clear and concise description of the task to implement.
      placeholder: "Task to implement..."
    validations:
      required: true

  - type: textarea
    id: tasks-to-complete
    attributes:
      label: Tasks to Complete
      description: What tasks need to be completed to implement this feature?
      placeholder: "- [ ] Task 1\n- [ ] Task 2\n- [ ] Task 3"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
    validations:
      required: false
